import {
  GOOGLE_MAPS_API_KEY,
  MAPBOX_ACCESS_TOKEN,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
  FIREBASE_DATABASE_URL,
} from '@env';

export const ENV = {
  MAPS: {
    GOOGLE_MAPS_API_KEY,
    MAPBOX_ACCESS_TOKEN,
  },
  FIREBASE: {
    API_KEY: FIREBASE_API_KEY,
    AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: FIREBASE_APP_ID,
    MEASUREMENT_ID: FIREBASE_MEASUREMENT_ID,
    DATABASE_URL: FIREBASE_DATABASE_URL,
  },
} as const;

// Type definitions for environment variables
declare module '@env' {
  export const GOOGLE_MAPS_API_KEY: string;
  export const MAPBOX_ACCESS_TOKEN: string;
  export const FIREBASE_API_KEY: string;
  export const FIREBASE_AUTH_DOMAIN: string;
  export const FIREBASE_PROJECT_ID: string;
  export const FIREBASE_STORAGE_BUCKET: string;
  export const FIREBASE_MESSAGING_SENDER_ID: string;
  export const FIREBASE_APP_ID: string;
  export const FIREBASE_MEASUREMENT_ID: string;
  export const FIREBASE_DATABASE_URL: string;
} 