version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: adorable_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-adorable_db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - adorable_network
    restart: unless-stopped

networks:
  adorable_network:
    driver: bridge

volumes:
  postgres: 