# Generated by Django 4.2.9 on 2025-02-23 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', 'is_primary'], name='locations_l_user_id_0a1ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'name')},
        ),
    ]
